export const TYPE_MODAL = {
  SEEDS: "SEEDS",
  MISSION: "MISSION",
  REFERRAL: "REFERRAL",
  GAMES: "GAMES",
  PROFILE: "PROFILE",
  WITHDRAW: "WITHDRAW",
  LUCKYWEEL: "LUCKYWEEL",
  LOTTERY: "LOTTERY",
  TICKETS: "TICKETS",
  DEPOSIT: "DEPOSIT",
  RANKING: "RANKING",
  UNLOCK_LAND: "UNLOCK_LAND"
};

export const TYPE_LOADING = {
  APP: 'APP',
  LOAD_SCREEN:'LOAD_SCREEN'
}