export const IS_OPEN = {
  SEEDS: "SEEDS",
  MISSION: "MISSION",
  REFERRAL: "REFERRAL",
  GAMES: "GAMES",
  PROFILE: "PROFILE",
  WITHDRAW: "WITHDRAW",
  LUCKYWEEL: "LUCKYWEEL",
  LOTTERY: "LOTTERY",
  TICKETS:"TICKETS"
};
